[package]
name = "gh-xplr"
version = "0.1.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xplr = "0.18.0"

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
